### ISSUE TITLE
duplicity backups on s3

### ISSUE THREAD

**Issue by atifmian** [openemr/openemr-devops#168]
when i run   /etc/cron.daily/duplicity-backups i get the following:

Traceback (most recent call last):
  File "/usr/bin/duplicity", line 1532, in <module>    with_tempdir(main)
  File "/usr/bin/duplicity", line 1526, in with_tempdir    fn()
  File "/usr/bin/duplicity", line 1364, in main    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1116, i                                                                                                                   n ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1005, i                                                                                                                     n set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 223, in get                                                                                                                     _backend
    obj = get_backend_object(url_string)
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 209, in get                                                                                                                     _backend_object
    return factory(pu)
  File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", li                                                                                                                     ne 161, in __init__
    self.resetConnection()
  File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", li                                                                                                                     ne 187, in resetConnection
    if "NoSuchBucket" in e.error_code:

TypeError: argument of type 'NoneType' is not iterable

any suggestions?

I am using Openemr standard on AWS, used cloudformation to deploy and it is working fine but can not backup and restore

thanks

**Comment by daurrutia** [comment]
tried as root?

**Comment by jesdynf** [comment]
It looks like it's angry because it can't find the S3 bucket it's looking for. Does that bucket still exist? Check your CloudFormation outputs for the bucket it should be trying to write to.

**Comment by atifmian** [comment]
is that bucket automatically created or do I need to create it? CF template does have a S3 bucket created
