### ISSUE TITLE
docker build is broken

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#199]
When build openemr docker set(s), am getting following error:
```
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.1.1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Obtaining file:///opt/certbot/acme
Obtaining file:///opt/certbot
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/certbot/setup.py", line 61, in <module>
        if StrictVersion(setuptools_version) >= StrictVersion('36.2'):
      File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
        raise ValueError, "invalid version number '%s'" % vstring
    ValueError: invalid version number '40.6.3.post20190116'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /opt/certbot/
The command '/bin/sh -c apk add --no-cache git build-base libffi-dev python-dev     && git clone https://github.com/openemr/openemr.git --depth 1     && rm -rf openemr/.git     && cd openemr     && composer install     && npm install --unsafe-perm     && npm run build     && composer global require phing/phing     && /root/.composer/vendor/bin/phing vendor-clean     && /root/.composer/vendor/bin/phing assets-clean     && composer global remove phing/phing     && composer dump-autoload -o     && composer clearcache     && npm cache clear --force     && rm -fr node_modules     && cd ../     && chmod 666 openemr/sites/default/sqlconf.php     && chown -R apache openemr/     && mv openemr /var/www/localhost/htdocs/     && git clone https://github.com/letsencrypt/letsencrypt /opt/certbot     && pip install --upgrade pip     && pip install -e /opt/certbot/acme -e /opt/certbot     && mkdir -p /etc/ssl/certs /etc/ssl/private     && apk del --no-cache git build-base libffi-dev python-dev' returned a non-zero code: 1
```

The related code in dockerbuild is here:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/5.0.2/Dockerfile#L37-L39

Any thoughts @TheToolBox , @jesdynf , @d3sandoval, @danehrlich1 ?

**Comment by bradymiller** [comment]
Would it make sense to pin the following clone call to a specific tag:
```
&& git clone https://github.com/letsencrypt/letsencrypt /opt/certbot \
```
Otherwise we are using master branch from that repo, which I am guessing where the above bug is coming from (ie. guessing a temporary break until it is fixed).

**Comment by bradymiller** [comment]
It worked when I pinned the branch on the above clone. So will bring that fix in. And we'll have to increment it every once and awhile.

**Comment by bradymiller** [comment]
fix is here:
https://github.com/openemr/openemr-devops/commit/fba329727960778c428978487a889ec6e31fefe8
