### ISSUE TITLE
unable to build arm7 dockers

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#321]
Have been unable to build the arm7 dockers for at least a month now, so gonna drop it for now (will just be temporary and will plan to intermittently attempt the builds with arm7. here is the error that is happening (have been unable to figure out how to fix it, but these things generally go away with time as the bug(s) in underlying package(s) are fixed:
```
#0 381.8 Building wheels for collected packages: cryptography
#0 381.8   Building wheel for cryptography (pyproject.toml): started
#0 489.6   Building wheel for cryptography (pyproject.toml): still running...
#0 810.0   Building wheel for cryptography (pyproject.toml): still running...
#0 906.1   Building wheel for cryptography (pyproject.toml): still running...
#0 906.4   Building wheel for cryptography (pyproject.toml): finished with status 'error'
#0 906.7   error: subprocess-exited-with-error
#0 906.7   
#0 906.7   × Building wheel for cryptography (pyproject.toml) did not run successfully.
#0 906.7   │ exit code: 1
#0 906.7   ╰─> [247 lines of output]
#0 906.7       running bdist_wheel
#0 906.7       running build
#0 906.7       running build_py
#0 906.7       creating build
#0 906.7       creating build/lib.linux-armv7l-cpython-39
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography
#0 906.7       copying src/cryptography/exceptions.py -> build/lib.linux-armv7l-cpython-39/cryptography
#0 906.7       copying src/cryptography/fernet.py -> build/lib.linux-armv7l-cpython-39/cryptography
#0 906.7       copying src/cryptography/__about__.py -> build/lib.linux-armv7l-cpython-39/cryptography
#0 906.7       copying src/cryptography/utils.py -> build/lib.linux-armv7l-cpython-39/cryptography
#0 906.7       copying src/cryptography/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/x509
#0 906.7       copying src/cryptography/x509/name.py -> build/lib.linux-armv7l-cpython-39/cryptography/x509
#0 906.7       copying src/cryptography/x509/extensions.py -> build/lib.linux-armv7l-cpython-39/cryptography/x509
#0 906.7       copying src/cryptography/x509/oid.py -> build/lib.linux-armv7l-cpython-39/cryptography/x509
#0 906.7       copying src/cryptography/x509/ocsp.py -> build/lib.linux-armv7l-cpython-39/cryptography/x509
#0 906.7       copying src/cryptography/x509/general_name.py -> build/lib.linux-armv7l-cpython-39/cryptography/x509
#0 906.7       copying src/cryptography/x509/base.py -> build/lib.linux-armv7l-cpython-39/cryptography/x509
#0 906.7       copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-armv7l-cpython-39/cryptography/x509
#0 906.7       copying src/cryptography/x509/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/x509
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat
#0 906.7       copying src/cryptography/hazmat/_oid.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat
#0 906.7       copying src/cryptography/hazmat/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings
#0 906.7       copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/_serialization.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/_cipheralgorithm.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/_asymmetric.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends
#0 906.7       copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/openssl
#0 906.7       copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/openssl
#0 906.7       copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/openssl
#0 906.7       copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/openssl
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/serialization
#0 906.7       copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/serialization
#0 906.7       copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/serialization
#0 906.7       copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/serialization
#0 906.7       copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/serialization
#0 906.7       copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/serialization
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/types.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/asymmetric
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/twofactor
#0 906.7       copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/twofactor
#0 906.7       copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/twofactor
#0 906.7       copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/twofactor
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/kdf
#0 906.7       copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/kdf
#0 906.7       copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/kdf
#0 906.7       copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/kdf
#0 906.7       copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/kdf
#0 906.7       copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/kdf
#0 906.7       copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/kdf
#0 906.7       copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/kdf
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/ciphers
#0 906.7       copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/ciphers
#0 906.7       copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/ciphers
#0 906.7       copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/ciphers
#0 906.7       copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/ciphers
#0 906.7       copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/primitives/ciphers
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/backends/openssl
#0 906.7       running egg_info
#0 906.7       writing src/cryptography.egg-info/PKG-INFO
#0 906.7       writing dependency_links to src/cryptography.egg-info/dependency_links.txt
#0 906.7       writing requirements to src/cryptography.egg-info/requires.txt
#0 906.7       writing top-level names to src/cryptography.egg-info/top_level.txt
#0 906.7       reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
#0 906.7       reading manifest template 'MANIFEST.in'
#0 906.7       no previously-included directories found matching 'docs/_build'
#0 906.7       warning: no previously-included files found matching 'vectors'
#0 906.7       warning: no previously-included files matching '*' found under directory 'vectors'
#0 906.7       warning: no previously-included files matching '*' found under directory '.github'
#0 906.7       warning: no previously-included files found matching 'release.py'
#0 906.7       warning: no previously-included files found matching '.coveragerc'
#0 906.7       warning: no previously-included files found matching 'codecov.yml'
#0 906.7       warning: no previously-included files found matching '.readthedocs.yml'
#0 906.7       warning: no previously-included files found matching 'dev-requirements.txt'
#0 906.7       warning: no previously-included files found matching 'tox.ini'
#0 906.7       warning: no previously-included files found matching 'mypy.ini'
#0 906.7       warning: no previously-included files matching '*' found under directory '.circleci'
#0 906.7       adding license file 'LICENSE'
#0 906.7       adding license file 'LICENSE.APACHE'
#0 906.7       adding license file 'LICENSE.BSD'
#0 906.7       adding license file 'LICENSE.PSF'
#0 906.7       writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
#0 906.7       /tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:153: SetuptoolsDeprecationWarning:     Installing 'cryptography.hazmat.bindings._rust' as data is deprecated, please list it in `packages`.
#0 906.7           !!
#0 906.7       
#0 906.7       
#0 906.7           ############################
#0 906.7           # Package would be ignored #
#0 906.7           ############################
#0 906.7           Python recognizes 'cryptography.hazmat.bindings._rust' as an importable package, however it is
#0 906.7           included in the distribution as "data".
#0 906.7           This behavior is likely to change in future versions of setuptools (and
#0 906.7           therefore is considered deprecated).
#0 906.7       
#0 906.7           Please make sure that 'cryptography.hazmat.bindings._rust' is included as a package by using
#0 906.7           setuptools' `packages` configuration field or the proper discovery methods
#0 906.7           (for example by using `find_namespace_packages(...)`/`find_namespace:`
#0 906.7           instead of `find_packages(...)`/`find:`).
#0 906.7       
#0 906.7           You can read more about "package discovery" and "data files" on setuptools
#0 906.7           documentation page.
#0 906.7       
#0 906.7       
#0 906.7       !!
#0 906.7       
#0 906.7         check.warn(importable)
#0 906.7       copying src/cryptography/py.typed -> build/lib.linux-armv7l-cpython-39/cryptography
#0 906.7       creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
#0 906.7       copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
#0 906.7       copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
#0 906.7       copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
#0 906.7       copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
#0 906.7       running build_ext
#0 906.7       running build_rust
#0 906.7           Updating crates.io index
#0 906.7       warning: spurious network error (2 tries remaining): failed to mmap. Could not write data: Out of memory; class=Os (2)
#0 906.7       warning: spurious network error (1 tries remaining): failed to mmap. Could not write data: Out of memory; class=Os (2)
#0 906.7       error: failed to get `asn1` as a dependency of package `cryptography-rust v0.1.0 (/tmp/pip-install-5ufbjql2/cryptography_b5e39ef71ba74ef198744d8e09eb23fc/src/rust)`
#0 906.7       
#0 906.7       Caused by:
#0 906.7         failed to fetch `https://github.com/rust-lang/crates.io-index`
#0 906.7       
#0 906.7       Caused by:
#0 906.7         failed to mmap. Could not write data: Out of memory; class=Os (2)
#0 906.7       
#0 906.7           =============================DEBUG ASSISTANCE=============================
#0 906.7           If you are seeing a compilation error please try the following steps to
#0 906.7           successfully install cryptography:
#0 906.7           1) Upgrade to the latest pip and try again. This will fix errors for most
#0 906.7              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
#0 906.7           2) Read https://cryptography.io/en/latest/installation/ for specific
#0 906.7              instructions for your platform.
#0 906.7           3) Check our frequently asked questions for more information:
#0 906.7              https://cryptography.io/en/latest/faq/
#0 906.7           4) Ensure you have a recent Rust toolchain installed:
#0 906.7              https://cryptography.io/en/latest/installation/#rust
#0 906.7       
#0 906.7           Python: 3.9.7
#0 906.7           platform: Linux-5.17.5-76051705-generic-armv7l-with
#0 906.7           pip: n/a
#0 906.7           setuptools: 62.3.2
#0 906.7           setuptools_rust: 1.3.0
#0 906.7           =============================DEBUG ASSISTANCE=============================
#0 906.7       
#0 906.7       Traceback (most recent call last):
#0 906.7         File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#0 906.7           main()
#0 906.7         File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#0 906.7           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 906.7         File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
#0 906.7           return _build_backend().build_wheel(wheel_directory, config_settings,
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 244, in build_wheel
#0 906.7           return self._build_with_temp_dir(['bdist_wheel'], '.whl',
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
#0 906.7           self.run_setup()
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
#0 906.7           exec(compile(code, __file__, 'exec'), locals())
#0 906.7         File "setup.py", line 39, in <module>
#0 906.7           setup(
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
#0 906.7           return distutils.core.setup(**attrs)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
#0 906.7           return run_commands(dist)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
#0 906.7           dist.run_commands()
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
#0 906.7           self.run_command(cmd)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
#0 906.7           super().run_command(command)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
#0 906.7           cmd_obj.run()
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
#0 906.7           self.run_command('build')
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
#0 906.7           self.distribution.run_command(command)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
#0 906.7           super().run_command(command)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
#0 906.7           cmd_obj.run()
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 136, in run
#0 906.7           self.run_command(cmd_name)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
#0 906.7           self.distribution.run_command(command)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
#0 906.7           super().run_command(command)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
#0 906.7           cmd_obj.run()
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools_rust/setuptools_ext.py", line 124, in run
#0 906.7           build_rust.run()
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools_rust/command.py", line 101, in run
#0 906.7           self.run_for_extension(ext)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 112, in run_for_extension
#0 906.7           dylib_paths = self.build_extension(ext, self.target)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 143, in build_extension
#0 906.7           target_dir = _base_cargo_target_dir(ext)
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 690, in _base_cargo_target_dir
#0 906.7           target_directory = ext._metadata()["target_directory"]
#0 906.7         File "/tmp/pip-build-env-2zkcqr4_/overlay/lib/python3.9/site-packages/setuptools_rust/extension.py", line 225, in _metadata
#0 906.7           self._cargo_metadata = json.loads(subprocess.check_output(metadata_command))
#0 906.7         File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
#0 906.7           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#0 906.7         File "/usr/lib/python3.9/subprocess.py", line 528, in run
#0 906.7           raise CalledProcessError(retcode, process.args,
#0 906.7       subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'src/rust/Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
#0 906.7       [end of output]
#0 906.7   
#0 906.7   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 906.7   ERROR: Failed building wheel for cryptography
#0 906.7 Failed to build cryptography
#0 906.7 ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
------
Dockerfile:26
--------------------
  25 |     #  btw, when this is fixed and we apk del build-base, this will decrease size of docker by 190MB :)
  26 | >>> RUN apk add --no-cache build-base libffi-dev python3-dev cargo \
  27 | >>>     && mkdir -p /var/www/localhost/htdocs/openemr/sites \
  28 | >>>     && chown -R apache /var/www/localhost/htdocs/openemr \
  29 | >>>     && git clone https://github.com/letsencrypt/letsencrypt --depth 1 /opt/certbot \
  30 | >>>     && pip install --upgrade pip \
  31 | >>>     && pip install -e /opt/certbot/acme -e /opt/certbot/certbot \
  32 | >>>     && mkdir -p /etc/ssl/certs /etc/ssl/private \
  33 | >>>     && apk del --no-cache libffi-dev python3-dev cargo \
  34 | >>>     && sed -i 's/^ *CustomLog/#CustomLog/' /etc/apache2/httpd.conf \
  35 | >>>     && sed -i 's/^ *ErrorLog/#ErrorLog/' /etc/apache2/httpd.conf \
  36 | >>>     && sed -i 's/^ *CustomLog/#CustomLog/' /etc/apache2/conf.d/ssl.conf \
  37 | >>>     && sed -i 's/^ *TransferLog/#TransferLog/' /etc/apache2/conf.d/ssl.conf
  38 |         
--------------------
error: failed to solve: process "/bin/sh -c apk add --no-cache build-base libffi-dev python3-dev cargo     && mkdir -p /var/www/localhost/htdocs/openemr/sites     && chown -R apache /var/www/localhost/htdocs/openemr     && git clone https://github.com/letsencrypt/letsencrypt --depth 1 /opt/certbot     && pip install --upgrade pip     && pip install -e /opt/certbot/acme -e /opt/certbot/certbot     && mkdir -p /etc/ssl/certs /etc/ssl/private     && apk del --no-cache libffi-dev python3-dev cargo     && sed -i 's/^ *CustomLog/#CustomLog/' /etc/apache2/httpd.conf     && sed -i 's/^ *ErrorLog/#ErrorLog/' /etc/apache2/httpd.conf     && sed -i 's/^ *CustomLog/#CustomLog/' /etc/apache2/conf.d/ssl.conf     && sed -i 's/^ *TransferLog/#TransferLog/' /etc/apache2/conf.d/ssl.conf" did not complete successfully: exit code: 1
```

**Comment by jesdynf** [comment]
Might be your environment -- are you building them in parallel? This is the
gripe...

0 906.7           Updating crates.io index

#0 906.7       warning: spurious network error (2 tries remaining):
failed to mmap. Could not write data: Out of memory; class=Os (2)

#0 906.7       warning: spurious network error (1 tries remaining):
failed to mmap. Could not write data: Out of memory; class=Os (2)

#0 906.7       error: failed to get `asn1` as a dependency of package
`cryptography-rust v0.1.0
(/tmp/pip-install-5ufbjql2/cryptography_b5e39ef71ba74ef198744d8e09eb23fc/src/rust)`

#0 906.7

#0 906.7       Caused by:

#0 906.7         failed to fetch
`https://github.com/rust-lang/crates.io-index`
<https://github.com/rust-lang/crates.io-index>

#0 906.7

#0 906.7       Caused by:

#0 906.7         failed to mmap. Could not write data: Out of memory;
class=Os (2)

**Comment by bradymiller** [comment]
been trying to sort this out with no luck.

Found what seemed to be a potential fix at https://github.com/pyca/cryptography/issues/6673#issuecomment-985943023 which did not work. Also tried going to lower versions of moby/buildkit and certbot with no luck.

The more I look into this, the more it looks like projects have been dropping support for arm7 over the last year. Hopefully we don't end up in that group :)

**Comment by bradymiller** [comment]
btw, also tried building in series rather than parallel and no funny business is happening with memory during the builds
